services:
  postgres:
    image: postgres:16
    container_name: job-platform-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_platform
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: job-platform-redis
    ports:
      - "6381:6379"
